export const PLAY_SONG = "PLAY_SONG";
export const SEARCH_SONG = "SEARCH_SONG";
export const UPDATE_QUERY = "UPDATE_QUERY";
export const M3TUBE_KEY = "AIzaSyB-CD2qqObMMMCUthOT1bV8bz32XmZ9pmE";
// export const M3TUBE_KEY = "AIzaSyCzJ3rS9ATMHTC0suSCA8G0fk0cZ7yWKec";
export const M3TUBE_URL = "https://www.googleapis.com/youtube/v3";
export const CHANGE_PAGINATION = "CHANGE_PAGINATION";
export const SHOW_ERROR = "SHOW_ERROR";
export const HIDE_ERROR = "HIDE_ERROR";
